CREATE SCHEMA IF NOT EXISTS `smallSiteDb` DEFAULT CHARACTER SET utf8 ;
USE `smallSiteDb` ;

CREATE TABLE IF NOT EXISTS `smallSiteDb`.`UNIDADE_FEDERATIVA` (
  `SGL_UNIDADE_FEDERATIVA` VARCHAR(2) NOT NULL,
  `NOM_UNIDADE_FEDERATIVA` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`SGL_UNIDADE_FEDERATIVA`));


CREATE TABLE IF NOT EXISTS `smallSiteDb`.`MUNICIPIO` (
  `COD_MUNICIPIO` INT NOT NULL,
  `NOM_MUNICIPIO` VARCHAR(100) NOT NULL,
  `NUM_POPULACAO` INT NULL,
  `NOM_PREFEITO` VARCHAR(100) NULL,
  `SGL_UNIDADE_FEDERATIVA` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`COD_MUNICIPIO`),
    FOREIGN KEY (`SGL_UNIDADE_FEDERATIVA`)
    REFERENCES `smallSiteDb`.`UNIDADE_FEDERATIVA` (`SGL_UNIDADE_FEDERATIVA`)
);

